
drop table toy CASCADE CONSTRAINTS;
drop table toy_basket CASCADE CONSTRAINTS;
drop table toy_board CASCADE CONSTRAINTS;
drop table toy_member CASCADE CONSTRAINTS;
drop table toy_pay CASCADE CONSTRAINTS;
drop table toy_rental CASCADE CONSTRAINTS;
drop sequence TOY_SEQ;
drop sequence PAY_SEQ;

SELECT COUNT(*) FROM toy_basket;


CREATE SEQUENCE TOY_SEQ --시퀀스이름 EX_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
NOCYCLE --순한하지않음

CREATE SEQUENCE TOY_BOARD_SEQ --시퀀스이름 TOY_BOARD_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
NOCYCLE --순한하지않음

CREATE SEQUENCE BASKET_SEQ --시퀀스이름 BASKET_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
NOCYCLE --순한하지않음

CREATE SEQUENCE PAY_SEQ --시퀀스이름 BASKET_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
NOCYCLE --순한하지않음




select * from toy;
select * from TOY_RENTAL;
select * from TOY_PAY;
select * from TOY_MEMBER
select * from TOY_BASKET;
insert into toy(name,domain,develop,age,rent,img) values()
TRUNCATE TABLE TOY_BASKET;
select toy_no from toy_basket where id ='a';
insert into toy_pay(no,id,discount,place,pay_year,toy_no) values(PAY_SEQ.NEXTVAL,1,1,1,1,1)
insert into toy_rental values(394,1,SYSDATE + 7)

--------------------------------------------------------
--  DDL for Table TOY
--------------------------------------------------------
  CREATE TABLE "HR"."TOY" 
   (	"NO" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DOMAIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DEVELOP" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"AGE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RENT" NUMBER DEFAULT 0, 
	"IMG" VARCHAR2(200 BYTE), 
	"EXPLAIN" VARCHAR2(300 BYTE), 
	 CONSTRAINT "TOY_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NO IS NULL THEN
      SELECT TOY_SEQ.NEXTVAL INTO :NEW.NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


--------------------------------------------------------
--  DDL for Table TOY_BASKET
--------------------------------------------------------

  CREATE TABLE "HR"."TOY_BASKET" 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(15 BYTE), 
	"TOY_NO" NUMBER
   );
--------------------------------------------------------
--  DDL for Table TOY_BOARD
--------------------------------------------------------

  CREATE TABLE "HR"."TOY_BOARD" 
   (	"NO" NUMBER, 
	"NAME" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(15 BYTE), 
	"CONTENT" VARCHAR2(400 BYTE), 
	"TITLE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOY_MEMBER
--------------------------------------------------------

  CREATE TABLE "HR"."TOY_MEMBER" 
   (	"ID" VARCHAR2(15 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"SALETARGET" NUMBER DEFAULT 1, 
	"TERM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOY_PAY
--------------------------------------------------------

  CREATE TABLE TOY_PAY 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(15 BYTE), 
	"DISCOUNT" NUMBER, 
	"PLACE" NUMBER, 
	"PAY_YEAR" VARCHAR2(20 BYTE) DEFAULT 1, 
	"TOY_NO" NUMBER, 
	"TOTAL" NUMBER
   ) 
--------------------------------------------------------
--  DDL for Table TOY_RENTAL
--------------------------------------------------------

  CREATE TABLE "HR"."TOY_RENTAL" 
   (	"NO" NUMBER, 
	"PLACE" NUMBER, 
	"EXPDATE" DATE
   ) 
--------------------------------------------------------
--  DDL for Index TOY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TOY_PK" ON "HR"."TOY" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOY_BASKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TOY_BASKET_PK" ON "HR"."TOY_BASKET" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."BOARD_PK" ON "HR"."TOY_BOARD" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOY_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TOY_MEMBER_PK" ON "HR"."TOY_MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOY_PAY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TOY_PAY_PK" ON "HR"."TOY_PAY" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOY_RENTAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TOY_RENTAL_PK" ON "HR"."TOY_RENTAL" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TOY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."TOY_TRG" BEFORE INSERT ON TOY FOR EACH ROW   <<COLUMN_SEQUENCES>>  BEGIN    IF INSERTING AND :NEW.NO IS NULL THEN      SELECT TOY_SEQ.NEXTVAL INTO :NEW.NO FROM SYS.DUAL
/
ALTER TRIGGER "HR"."TOY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TOY_BASKET_TRG
--------------------------------------------------------

--  CREATE OR REPLACE TRIGGER "HR"."TOY_BASKET_TRG" 
--BEFORE INSERT ON TOY_BASKET 
--FOR EACH ROW 
--BEGIN
--  <<COLUMN_SEQUENCES>>
--  BEGIN
--    IF INSERTING AND :NEW.NO IS NULL THEN
--      SELECT TOY_BASKET_SEQ.NEXTVAL INTO :NEW.NO FROM SYS.DUAL
--/
--ALTER TRIGGER "HR"."TOY_BASKET_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOARD_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."BOARD_TRG" 
BEFORE INSERT ON TOY_BOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL
/
ALTER TRIGGER "HR"."BOARD_TRG" ENABLE;

--------------------------------------------------------
--  Constraints for Table TOY_BASKET
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_BASKET" ADD CONSTRAINT "TOY_BASKET_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TOY_BASKET" MODIFY ("TOY_NO" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_BASKET" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_BASKET" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOY_BOARD
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TOY_BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_BOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_BOARD" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOY_MEMBER
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_MEMBER" ADD CONSTRAINT "TOY_MEMBER_CHK1" CHECK (saletarget = 1 OR saletarget = 2) ENABLE;
  ALTER TABLE "HR"."TOY_MEMBER" ADD CONSTRAINT "TOY_MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TOY_MEMBER" MODIFY ("SALETARGET" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOY_PAY
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "TOY_PAY_PALCE_CHK1" CHECK (place = 0 or place = 1) ENABLE;
  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "TOY_PAY_YEAR_CHK1" CHECK (pay_year = 0 or pay_year = 1) ENABLE;
  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "TOY_PAY_DISCOUNT_CHK1" CHECK (discount = 1 or discount = 2) ENABLE;
  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "PAY_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("TOY_NO" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("PAY_YEAR" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_PAY" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOY_RENTAL
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_RENTAL" ADD CONSTRAINT "TOY_RENTAL_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."TOY_RENTAL" MODIFY ("EXPDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_RENTAL" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TOY_RENTAL" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TOY_BASKET
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_BASKET" ADD CONSTRAINT "TOY_BASKET_FK1" FOREIGN KEY ("ID")
	  REFERENCES "HR"."TOY_MEMBER" ("ID") ENABLE;
  ALTER TABLE "HR"."TOY_BASKET" ADD CONSTRAINT "TOY_BASKET_FK2" FOREIGN KEY ("TOY_NO")
	  REFERENCES "HR"."TOY" ("NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOY_BOARD
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_BOARD" ADD CONSTRAINT "BOARD_FK1" FOREIGN KEY ("ID")
	  REFERENCES "HR"."TOY_MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOY_PAY
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "PAY_MEM_ID_FK1" FOREIGN KEY ("ID")
	  REFERENCES "HR"."TOY_MEMBER" ("ID") ENABLE;
  ALTER TABLE "HR"."TOY_PAY" ADD CONSTRAINT "PAY_TOY_NO_FK2" FOREIGN KEY ("TOY_NO")
	  REFERENCES "HR"."TOY" ("NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOY_RENTAL
--------------------------------------------------------

  ALTER TABLE "HR"."TOY_RENTAL" ADD CONSTRAINT "TOY_RENTAL_FK1" FOREIGN KEY ("NO")
	  REFERENCES "HR"."TOY" ("NO") ENABLE;
